name: Actualizacion Diaria Monitor Campo

on:
  schedule:
    # Se ejecuta a las 07:00 AM (hora España aprox.) de lunes a viernes
    - cron: '0 6 * * 1-5'
  workflow_dispatch: # Permite que tú lo ejecutes a mano cuando quieras

jobs:
  run_scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerias
        run: pip install -r requirements.txt
        
       #- name: Instalar librerias
       # run: 
       #   python -m pip install --upgrade pip
       #   pip install supabase requests pandas beautifulsoup4 python-dotenv

      - name: Ejecutar Monitor
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python monitor_agrotech_v1.py #este es el nombre actual del archivo python
