name: Recuperacion Manual de Datos

on:
  workflow_dispatch: # Esto es lo que crea el bot√≥n "Run workflow"

jobs:
  recuperar:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerias
        run: pip install supabase requests

      - name: Ejecutar Script de Rescate
        run: python recuperar_energia.py
